- name: install nginx
  hosts: frontend
  become: yes
  tasks:
  - name: print some facts
    debug:
        msg: "{{ ansible_facts }}"
  - name: print some facts
    debug:
        msg: "OS: {{ ansible_user_shell }}"
  - name: install nginx
    package:
      name: nginx
      state: installed

  - name: start and enable nginx
    service:
      name: nginx
      state: started
      enabled: yes