- name: install nginx
  hosts: frontend
  become: yes
  gather_facts: false
  tasks:
  - name: print some facts
    debug:
        msg: "OS is {{ ansible_distribution }} {{ ansible_distribution_version }}"
  - name: install nginx
    package:
      name: nginx
      state: installed

  - name: start and enable nginx
    service:
      name: nginx
      state: started
      enabled: yes